name: prepare a new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Bump the version and edit the changelog
        run: |
          yarn install
          yarn version $VERSION
          yarn conventional-changelog -p conventionalcommits -i CHANGELOG.md -s
          git add CHANGELOG.md package.json
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Create release PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.JLG_ACCESS_TOKEN }}
          branch: "release/${{ github.event.inputs.version }}"
          title: "[Release] V${{ github.event.inputs.version }}"
          body: "Release ${{ github.event.inputs.version }}"
          committer: "Node-config Bot <noreply@github.com>"
          commit-message: "chore(release): bump version to ${{ github.event.inputs.version }}"
          labels: release
          delete-branch: true
          base: master
